#Arrays

In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
b=[]
for i in range(0,5):
    c=int(input("Enter the number:"))
    b.append(c)
d=np.array(b)
print(d)

Enter the number: 8
Enter the number: 6
Enter the number: 4
Enter the number: 8
Enter the number: 7


[8 6 4 8 7]


In [5]:
e=[2,4,5,3,8,9]
f=np.array(e)
print(f)
print(type(f))

[2 4 5 3 8 9]
<class 'numpy.ndarray'>
