In [3]:
import numpy as np
var=np.array([1,3,5,7])
var_1=np.array([2,4,6,8])
print(var+var_1)
print(var-var_1)
print(var*var_1)
print(var/var_1)
print(var%var_1)
print(var**var_1)
print(1/var)
print(1/var_1)

[ 3  7 11 15]
[-1 -1 -1 -1]
[ 2 12 30 56]
[0.5        0.75       0.83333333 0.875     ]
[1 3 5 7]
[      1      81   15625 5764801]
[1.         0.33333333 0.2        0.14285714]
[0.5        0.25       0.16666667 0.125     ]


In [6]:
var=np.array([1,3,5,7])
var_1=np.array([2,4,6,8])
print(np.add(var,var_1))
print(np.subtract(var,var_1))
print(np.multiply(var,var_1))
print(np.divide(var,var_1))
print(np.mod(var,var_1))
print(np.power(var,var_1))
print(np.reciprocal(var))
print(np.reciprocal(var_1))

[ 3  7 11 15]
[-1 -1 -1 -1]
[ 2 12 30 56]
[0.5        0.75       0.83333333 0.875     ]
[1 3 5 7]
[      1      81   15625 5764801]
[1 0 0 0]
[0 0 0 0]


In [7]:
var=np.array([1,3,5,7])
print(var+3)
print(var-3)
print(var*3)
print(var/3)
print(var%3)
print(var**3)

[ 4  6  8 10]
[-2  0  2  4]
[ 3  9 15 21]
[0.33333333 1.         1.66666667 2.33333333]
[1 0 2 1]
[  1  27 125 343]


In [9]:
var=np.array([[1,3,5,7],[2,4,6,8]])
var_1=np.array([[2,4,6,8],[1,4,5,7]])
print(np.add(var,var_1))
print(np.subtract(var,var_1))
print(np.multiply(var,var_1))
print(np.divide(var,var_1))
print(np.mod(var,var_1))
print(np.power(var,var_1))

[[ 3  7 11 15]
 [ 3  8 11 15]]
[[-1 -1 -1 -1]
 [ 1  0  1  1]]
[[ 2 12 30 56]
 [ 2 16 30 56]]
[[0.5        0.75       0.83333333 0.875     ]
 [2.         1.         1.2        1.14285714]]
[[1 3 5 7]
 [0 0 1 1]]
[[      1      81   15625 5764801]
 [      2     256    7776 2097152]]
