In [1]:
import numpy as np
var=np.array([1,3,5,7])
print(np.max(var))
print(np.min(var))

7
1


In [4]:
var_1=np.array([1,3,5,7])
print(np.max(var_1),np.argmax(var_1))
print(np.min(var_1),np.argmin(var_1))

7 3
1 0


In [6]:
var_2=np.array([1,3,5,7])
print(np.sin(var_2))
print(np.cos(var_2))
print(np.cumsum(var_2))

[ 0.84147098  0.14112001 -0.95892427  0.6569866 ]
[ 0.54030231 -0.9899925   0.28366219  0.75390225]
[ 1  4  9 16]


In [9]:
var_2=np.array([1,3,5,7,16])
print(np.sqrt(var_2))

[1.         1.73205081 2.23606798 2.64575131 4.        ]


In [10]:
var_2=np.array([[1,3,5,7],[2,4,6,8]])
print(np.max(var_2,axis=0))
print(np.max(var_2,axis=1))
print(np.min(var_2,axis=0))
print(np.min(var_2,axis=1))

[2 4 6 8]
[7 8]
[1 3 5 7]
[1 2]
