In [2]:
import numpy as np
var=np.array([1,3,5,7,9])
var1=np.array([2,4,6,8])
print(var+var1)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [6]:
var2=np.array([[1,3,5,7,9],[2,4,6,8,0]])
var3=np.array([[2],[1]])
print(var2+var3)

[[ 3  5  7  9 11]
 [ 3  5  7  9  1]]


In [9]:
var=np.array([1,3,5,7,9])
var1=np.array([2])
c=var+var1
print(c)
print(c.shape)

[ 3  5  7  9 11]
(5,)


In [10]:
var6=np.array([[1],[2]])
var7=np.array([[1,2,3],[1,2,3]])
print(var6+var7)

[[2 3 4]
 [3 4 5]]
