Indexing of 1-D array

In [4]:
import numpy as np
var=np.array([1,3,5,7,9,2,4,6,8,0])
print(var[3:8])
print(var[3:])
print(var[:9])
print(var[:])
print(var[3:8:2])
print(var[-3])

[7 9 2 4 6]
[7 9 2 4 6 8 0]
[1 3 5 7 9 2 4 6 8]
[1 3 5 7 9 2 4 6 8 0]
[7 2 6]
6


In [5]:
var1=np.array([[1,3,5,7,9],[2,4,6,8,0]])
print(var1)
print(var1[0,2])
print(var1[1,3])
print(var1[0,-2])

[[1 3 5 7 9]
 [2 4 6 8 0]]
5
8
7


Slicing of an array