In [2]:
import numpy as np
var=np.array([2,4,6,7,9])
print(var)
print(var.ndim)
print(var.shape)

[2 4 6 7 9]
1
(5,)


In [4]:
var1=np.array([[2,4,6,7,9],[1,3,6,4,0]])
print(var1)
print(var1.ndim)
print(var1.shape)
print(var1.reshape(5,2))

[[2 4 6 7 9]
 [1 3 6 4 0]]
2
(2, 5)
[[2 4]
 [6 7]
 [9 1]
 [3 6]
 [4 0]]


In [6]:
var3=np.array([[[2,4,6,7,9],[1,3,6,4,0],[4,6,2,9,7]]])
print(var3)
print(var3.ndim)
print(var3.shape)
print(var3.reshape(3,5,1))
print()
print(var3.reshape(1,5,3))

[[[2 4 6 7 9]
  [1 3 6 4 0]
  [4 6 2 9 7]]]
3
(1, 3, 5)
[[[2]
  [4]
  [6]
  [7]
  [9]]

 [[1]
  [3]
  [6]
  [4]
  [0]]

 [[4]
  [6]
  [2]
  [9]
  [7]]]

[[[2 4 6]
  [7 9 1]
  [3 6 4]
  [0 4 6]
  [2 9 7]]]


1-D to 2-D

In [8]:
var=np.array([2,4,6,7,9,0])
print(var)
print(var.ndim)
print(var.shape)
print()
print()
print(var.reshape(3,2))

[2 4 6 7 9 0]
1
(6,)


[[2 4]
 [6 7]
 [9 0]]


1-D to 3-D

In [10]:
var=np.array([2,4,6,7,9,0])
print(var)
print(var.ndim)
print(var.shape)
print()
print()
print(var.reshape(1,3,2))
print()
print(var.reshape(2,3,1))

[2 4 6 7 9 0]
1
(6,)


[[[2 4]
  [6 7]
  [9 0]]]

[[[2]
  [4]
  [6]]

 [[7]
  [9]
  [0]]]


Convert anything into 1-D

In [11]:
var=np.array([2,4,6,7,9,0])
print(var)
print(var.ndim)
print(var.shape)
print()
print()
print(var.reshape(1,3,2))
print()
print(var.reshape(-1))

[2 4 6 7 9 0]
1
(6,)


[[[2 4]
  [6 7]
  [9 0]]]

[2 4 6 7 9 0]
