##Numpy array using numpy function
##Special numpy arrays

##zeros array

In [2]:
import numpy as np
arr=np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [4]:
arr=np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##ones array

In [7]:
ar_1=np.ones(4)
ar_2=np.ones((4,3))
print(ar_1)
print()
print(ar_2)

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##empty array

In [8]:
e=np.empty((4))
f=np.empty((4,3))
print(e)
print()
print(f)

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##for a range

In [9]:
ra=np.arange(0,5)
print(ra)

[0 1 2 3 4]


##linscape

In [11]:
li=np.linspace(0,12,5)
print(li)

[ 0.  3.  6.  9. 12.]


##diagonal elements with one's

In [12]:
dia=np.eye(4)
print(dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
