#TYPES OF ARRAY

##1-D array

In [2]:
import numpy as np
arr_1=np.array([2,3,5,6])
print(arr_1)
print(arr_1.ndim)
print(arr_1.shape)

[2 3 5 6]
1
(4,)


##2-D array

In [4]:
arr_2=np.array([[2,3,5,6],[1,9,8,7]])
print(arr_2)
print(arr_2.ndim)
print(arr_2.shape)

[[2 3 5 6]
 [1 9 8 7]]
2
(2, 4)


##3-D array

In [5]:
arr_3=np.array([[[2,3,5,6],[1,7,8,9],[3,6,4,8]]])
print(arr_3)
print(arr_3.ndim)
print(arr_3.shape)

[[[2 3 5 6]
  [1 7 8 9]
  [3 6 4 8]]]
3
(1, 3, 4)


##n dimensional array

In [8]:
arn=np.array([1,2,3,4],ndim=10)
print(arn)

TypeError: array() got an unexpected keyword argument 'ndim'