In [2]:
import numpy as np
var=np.random.rand(4)
print(var)

[0.06642417 0.16240667 0.53435707 0.22122814]


In [4]:
var=np.random.rand(2,2)
print(var)

[[0.81413691 0.29670558]
 [0.49878518 0.00748182]]


In [5]:
var_1=np.random.randn(5)
print(var_1)

[ 0.91412113  1.35429834 -2.36902786  0.35857712  0.21904135]


In [6]:
var_2=np.random.randn(5,5)
print(var_2)

[[-0.65273798 -1.64367715  1.0235143   0.51495214  0.63599527]
 [ 0.82122409 -0.48219233 -0.40055046  0.68735585  0.92176333]
 [-1.18679541 -0.16893214  2.13559978 -1.1269929  -0.36815244]
 [ 2.12800336 -1.37046773  0.0246486  -1.28508169  0.53486657]
 [ 0.84249662 -0.65002861  1.12072387  0.8748029  -0.79782881]]


In [7]:
var_3=np.random.randint(5,20,5)
print(var_3)

[19  9 14 16 13]


In [8]:
var_3=np.random.randint(5,20,(5,3))
print(var_3)

[[ 6  6  6]
 [13 11 16]
 [17 19 17]
 [14  8 18]
 [ 6 13 14]]


In [9]:
var_4=np.random.ranf(5)
print(var_4)

[0.27982535 0.86739259 0.68245764 0.05289399 0.68010928]
